### ISSUE TITLE
MIMIR benchmark: 13-gram data?

### ISSUE THREAD

**Issue by kirklandWater1** [zjysteven/mink-plus-plus#1]
Hi, thank you for the great work! Is the result from Table 2 in the paper coming from MIMIR 13-gram split [here](https://huggingface.co/datasets/iamgroot42/mimir/tree/main/cache_100_200_1000_512 )?

**Comment by zjysteven** [comment]
Hello, yes that is correct. It is a reproduced version of Table 11 in the original MIMIR paper. Code and instructions to run experiments on MIMIR are available in my fork [here](https://github.com/zjysteven/mimir).
