### ISSUE TITLE
Reference baseline

### ISSUE THREAD

**Issue by Salehzz** [zjysteven/mink-plus-plus#4]
Hi, I am running the code for the reference attack on MIMIR benchmark, and I don't get the same results as mentioned in the paper, the results are not even close:

your paper: Pythia 6.9b on Wikipedia -> 61.8 (Pythia 70m as the reference)
the result that I get -> 54.7

do you have any idea what might be the problem?

**Comment by zjysteven** [comment]
For reference method we are directly copying the numbers reported by MIMIR https://arxiv.org/pdf/2402.07841 in Table 11.

**Comment by Salehzz** [comment]
Thanks a lot for your quick reply.

**Comment by zjysteven** [comment]
No problem. Also we are using this exact split from MIMIR (https://huggingface.co/datasets/iamgroot42/mimir/tree/main/cache_100_200_1000_512). By checking the reproduced performance of other baselines (e.g. Loss) I remember that it can be confirmed that the numbers in Table 11 indeed are obtained on the linked data split.
