### ISSUE TITLE
Missing negative sign

### ISSUE THREAD

**Issue by king-menin** [zjysteven/mink-plus-plus#5]
Hi,
do you mean `-np.mean(topk_prob).item()` here: https://github.com/zjysteven/mink-plus-plus/blob/f0dbf96ea544edc0edc7393c2634cdcad66d484c/run.py#L106 and https://github.com/zjysteven/mink-plus-plus/blob/f0dbf96ea544edc0edc7393c2634cdcad66d484c/run.py#L113

**Comment by zjysteven** [comment]
No, the labels for training data and non-training data are 1 and 0, respectively
https://github.com/zjysteven/mink-plus-plus/blob/f0dbf96ea544edc0edc7393c2634cdcad66d484c/run.py#L124
so the scores of training data are expected to be larger than the scores of non-training data. If we negate the score for Min-K% and Min-K%++ then it would be the other way around (training data score smaller than non-training data score).
